version: '3.8'

services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3

  multicoder:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      redis:
        condition: service_healthy
    environment:
      - MULTICODER_REDIS_URL=redis://redis:6379/0
      - MULTICODER_LOG_LEVEL=INFO
    volumes:
      - ./:/app
    restart: unless-stopped

volumes:
  redis-data: